# Generated by Django 6.0.4 on 2026-04-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_alter_motorcycle_category_motorcycle_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('rating', models.IntegerField(default=5, verbose_name='Số sao (1-5)')),
                ('content', models.TextField(verbose_name='Nội dung đánh giá')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
