# Generated by Django 6.0.4 on 2026-04-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='colors',
            field=models.CharField(default='Đen', max_length=200, verbose_name='Màu sắc'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Giá bán'),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='version',
            field=models.CharField(default='Tiêu chuẩn', max_length=100, verbose_name='Phiên bản'),
        ),
    ]
