# Generated by Django 6.0.4 on 2026-04-19 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_motorcycle_colors_motorcycle_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorcycle',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='price',
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='version',
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Hãng xe'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Loại xe'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả chung'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='image',
            field=models.ImageField(blank=True, upload_to='motorcycles/', verbose_name='Hình ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên dòng xe'),
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(help_text='VD: Tiêu chuẩn, Thể thao...', max_length=100, verbose_name='Tên phiên bản')),
                ('color_name', models.CharField(max_length=100, verbose_name='Màu sắc')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá bán cho màu này')),
                ('motorcycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='shop.motorcycle', verbose_name='Thuộc dòng xe')),
            ],
        ),
    ]
