# Generated by Django 6.0.4 on 2026-04-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_motorcycle_colors_remove_motorcycle_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='color_name',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='version_name',
            new_name='name',
        ),
    ]
