# Generated by Django 6.0.4 on 2026-05-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_customer_birthday_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_scanned',
            field=models.BooleanField(default=False),
        ),
    ]
